### ISSUE TITLE
The "Ignore Update" Chat Message Doesn't Work

### ISSUE THREAD

**Issue by ALAND-MC** [vesmaybevesper/Am-I-Up-To-Date#10]
When I click the message to ignore updates and swap lobbies on Hypixel for example it just shows up again.

Version: 1.0.5-1.21.5Fabric

**Comment by vesmaybevesper** [comment]
interesting, sounds like the variable isn't updating properly. 1.0.5 was the last version to support 1.21.5 for fabric so it's possible this isn't an issue on newer version but i'd have to test that. i'm in the middle of re-writing the mod so a fix for this likely wont be out until the first release of that (this update includes changing the mappings so i should be able to support 1.21.5 for fabric again as a Yarn update was the issue)

**Comment by ALAND-MC** [comment]
Hope to see it fixed one day, and thank you for your efforts. :)

**Comment by vesmaybevesper** [comment]
I've just put out the first beta for the re-write. It supports 1.21.5 again, so if your modpack updates to it please let me know if it's fixed the issue for you! I had tried to move around Hypixel with the mod on for the latest versions but didn't experience this, so it may have been fixed in later releases.

**Comment by ALAND-MC** [comment]
tysm! I'll test and see if it has been fixed

**Comment by ALAND-MC** [comment]
@vesmaybevesper Hello! I tested and it does work. However, it only takes effect after restarting the game. Swapping lobbies still makes it appear on the same session.

**Comment by vesmaybevesper** [comment]
Hmm, okay. I'll try another fix for beta 2.

**Comment by vesmaybevesper** [comment]
I just released Beta 2, it has another attempt at fixing this, please let me know if it fixed it for you!

**Comment by vesmaybevesper** [comment]
Hiya, I'm (hopefully) closing in on the first full release of 2.0.0, and I'd love for this issue to be closed for that, is the issue still occurring or did the last fix attempt work?

**Comment by ALAND-MC** [comment]
I'll test and see.

**Comment by vesmaybevesper** [comment]
Thanks!

**Comment by ALAND-MC** [comment]
It's still not working. Same thing as previously. Using latest version for 1.21.10. I clicked the ignore button multiple times but no matter what when I swap worlds it still appears in chat.

**Comment by vesmaybevesper** [comment]
That's wild. I'm running out of ideas for what might be causing it, but I'll keep trying.

**Comment by vesmaybevesper** [comment]
Question while I explore this more, does this still happen if you manually run /shouldIgnore?

**Comment by ALAND-MC** [comment]
@vesmaybevesper It still happens.

**Comment by vesmaybevesper** [comment]
OK that at least gives me an idea of where the issue is located, thanks.

**Comment by vesmaybevesper** [comment]
OK, I managed to replicate the issue, and then I got it fixed for me (which hopefully means its totally fixed, but with how this issue has gone so far you never know). It'll be out in the full release which should be out soon!

**Comment by vesmaybevesper** [comment]
2.0.0 is published with this fix included!
